version: "3.7"

services:
  mongodb:
    image: mongo
    restart: always
  web:
    build: .
    command: flask run --host=0.0.0.0
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - mongodb